[workspace]

members = [
  "constants",
  "cstr",
  "odbc",
  "odbc-sys",
  "core",
  "integration_test",
  "win_setupgui",
  "shared_sql_utils",
  "logger",
  "macos_postinstall",
  "serde_test",
]

[profile.release]
debug = true
